export const cocktailDatabase = [
    { name: "Long Island Iced Tea", ingredients: { "Vodka": 15, "Gin": 15, "Rum": 15, "Tequila": 15, "Cointreau": 15, "Lemon": 20, "Sugar Syrup": 10, "Soda": 30 } },
    { name: "Tommy's Margarita", ingredients: { "Tequila": 60, "Lime": 30, "Sugar Syrup": 15 } },
    { name: "Daiquiri", ingredients: { "Rum": 60, "Lime": 30, "Sugar Syrup": 15 } },
    { name: "Cosmopolitan", ingredients: { "Vodka": 45, "Cointreau": 15, "Cranberry": 30, "Lime": 15 } },
    { name: "Sidecar", ingredients: { "Brandy": 50, "Cointreau": 20, "Lemon": 20 } },
    { name: "Kamikaze", ingredients: { "Vodka": 30, "Cointreau": 30, "Lime": 30 } },
    { name: "Tequila Sunrise", ingredients: { "Tequila": 50, "Orange": 100, "Cranberry": 10, "Sugar Syrup": 5 } },
    { name: "Sex on the Beach", ingredients: { "Vodka": 40, "Peach Schnapps": 20, "Orange": 60, "Cranberry": 60 } },
    { name: "Negroni", ingredients: { "Gin": 30, "Campari": 30, "Vermouth": 30 } },
    { name: "Old Fashioned", ingredients: { "Whiskey": 60, "Sugar Syrup": 10, "Bitters": 10 } },
    { name: "Black Russian", ingredients: { "Vodka": 50, "Kahlua": 20 } },
    { name: "Mudslide", ingredients: { "Vodka": 30, "Kahlua": 30, "Baileys": 30 } },
    { name: "Americano", ingredients: { "Campari": 30, "Vermouth": 30, "Soda": 60 } },
    { name: "Woo Woo", ingredients: { "Vodka": 40, "Peach Schnapps": 20, "Cranberry": 80 } },
    { name: "Amaretto Sour", ingredients: { "Amaretto": 60, "Lemon": 30, "Sugar Syrup": 15, "Egg White": 15, "Bitters": 10 } },
    { name: "Peach Vodka Spritz", ingredients: { "Vodka": 30, "Peach Schnapps": 30, "Soda": 90 } },
    { name: "Campari Spritz", ingredients: { "Campari": 60, "Soda": 90, "Lemon": 10 } },
    { name: "Rum Punch", ingredients: { "Rum": 60, "Orange": 60, "Lime": 20, "Sugar Syrup": 10 } },
    { name: "Martini", ingredients: { "Gin": 60, "Vermouth": 10 } },
    { name: "Whiskey Sour", ingredients: { "Whiskey": 60, "Lemon": 30, "Sugar Syrup": 15, "Egg White": 15 } },
    { name: "Blue Lagoon", ingredients: { "Vodka": 45, "Blue Curacao": 20, "Lemon": 20, "Soda": 60 } },
    { name: "Godfather", ingredients: { "Whiskey": 45, "Amaretto": 15 } },
    { name: "Electric Lemonade", ingredients: { "Vodka": 45, "Blue Curacao": 15, "Lemon": 30, "Sugar Syrup": 10, "Soda": 60 } },
    { name: "Fuzzy Navel", ingredients: { "Peach Schnapps": 60, "Orange": 120 } }
];
