export const cocktailDatabase = [
    { name: "Cosmopolitan", ingredients: { "Vodka": 45, "Cointreau": 15, "Cranberry": 30, "Lime": 15 }, idealShake: 5.0 },
    { name: "Screwdriver", ingredients: { "Vodka": 50, "Orange": 150 }, idealShake: 3.0 },
    { name: "Gin Fizz", ingredients: { "Gin": 45, "Lemon": 30, "Sugar Syrup": 15, "Soda": 30 }, idealShake: 6.0 },
    { name: "Daiquiri", ingredients: { "Rum": 50, "Lime": 25, "Sugar Syrup": 15 }, idealShake: 5.0 },
    { name: "Margarita", ingredients: { "Tequila": 50, "Cointreau": 20, "Lime": 15 }, idealShake: 5.0 },
    { name: "White Russian", ingredients: { "Vodka": 50, "Kahlua": 20 }, idealShake: 2.0 },
    { name: "Whiskey Sour", ingredients: { "Whiskey": 60, "Lemon": 30, "Sugar Syrup": 15, "Egg White": 15 }, idealShake: 6.0 },
    { name: "Martini", ingredients: { "Gin": 60, "Vermouth": 10 }, idealShake: 3.0 },
    { name: "Vodka Martini", ingredients: { "Vodka": 60, "Vermouth": 10 }, idealShake: 3.0 },
    { name: "Sidecar", ingredients: { "Brandy": 50, "Cointreau": 20, "Lemon": 20 }, idealShake: 5.0 },
    { name: "Tom Collins", ingredients: { "Gin": 50, "Lemon": 25, "Sugar Syrup": 15, "Soda": 60 }, idealShake: 4.0 },
    { name: "Tequila Sunrise", ingredients: { "Tequila": 50, "Orange": 100 }, idealShake: 2.0 },
    { name: "Kamikaze", ingredients: { "Vodka": 30, "Cointreau": 30, "Lime": 30 }, idealShake: 5.0 },
    { name: "Gimlet", ingredients: { "Gin": 60, "Lime": 20, "Sugar Syrup": 10 }, idealShake: 4.0 },
    { name: "Sea Breeze", ingredients: { "Vodka": 40, "Cranberry": 120, "Orange": 30 }, idealShake: 3.0 },
    { name: "Madras", ingredients: { "Vodka": 40, "Cranberry": 120, "Orange": 30 }, idealShake: 3.0 },
    { name: "Cape Codder", ingredients: { "Vodka": 50, "Cranberry": 100 }, idealShake: 2.0 },
    { name: "Paloma", ingredients: { "Tequila": 50, "Lime": 15, "Soda": 100 }, idealShake: 3.0 },
    { name: "Manhattan", ingredients: { "Whiskey": 50, "Vermouth": 20 }, idealShake: 3.0 },
    { name: "Black Russian", ingredients: { "Vodka": 50, "Kahlua": 20 }, idealShake: 2.0 },
    { name: "Lemon Drop", ingredients: { "Vodka": 45, "Cointreau": 15, "Lemon": 20, "Sugar Syrup": 10 }, idealShake: 6.0 },
    { name: "Old Fashioned", ingredients: { "Whiskey": 60, "Sugar Syrup": 10, "Bitters": 5 }, idealShake: 2.0 },
    { name: "Moscow Mule", ingredients: { "Vodka": 50, "Lime": 15, "Soda": 120 }, idealShake: 3.0 },
    { name: "Greyhound", ingredients: { "Vodka": 50, "Orange": 120 }, idealShake: 2.0 },
    { name: "Rum & Soda", ingredients: { "Rum": 50, "Soda": 120 }, idealShake: 3.0 },
    { name: "Gin & Soda", ingredients: { "Gin": 50, "Soda": 120 }, idealShake: 3.0 },
    { name: "Sake Sour", ingredients: { "Sake": 60, "Lemon": 20, "Sugar Syrup": 15, "Egg White": 15 }, idealShake: 5.0 },
    { name: "Brandy Alexander", ingredients: { "Brandy": 40, "Kahlua": 30 }, idealShake: 5.0 },
    { name: "Tequila Sour", ingredients: { "Tequila": 50, "Lemon": 25, "Sugar Syrup": 20, "Egg White": 15 }, idealShake: 6.0 },
    { name: "Mojito", ingredients: { "Rum": 50, "Lime": 25, "Sugar Syrup": 20, "Soda": 60 }, idealShake: 6.0 },
    { name: "Long Island Ice Tea", ingredients: { "Vodka": 15, "Gin": 15, "Rum": 15, "Tequila": 15, "Cointreau": 15, "Lemon": 20, "Sugar Syrup": 15, "Soda": 40 }, idealShake: 4.0 },
    { name: "Amaretto Sour", ingredients: { "Amaretto": 60, "Lemon": 30, "Sugar Syrup": 15, "Egg White": 15 }, idealShake: 6.0 },
    { name: "Negroni", ingredients: { "Gin": 30, "Vermouth": 30, "Campari": 30 }, idealShake: 3.0 },
    { name: "Sex on the Beach", ingredients: { "Vodka": 45, "Peach Schnapps": 15, "Orange": 60, "Cranberry": 60 }, idealShake: 5.0 },
    { name: "B-52", ingredients: { "Kahlua": 20, "Baileys": 20, "Cointreau": 20 }, idealShake: 2.0 },
    { name: "Blue Margarita", ingredients: { "Tequila": 45, "Blue Curacao": 15, "Lime": 30 }, idealShake: 5.0 }
];
